site_name: EO Exploitation Platform Common Architecture
# site_url: https://deployment-guide.docs.eoepca.org
# repo_url: https://github.com/EOEPCA/deployment-guide
# edit_uri: ""

nav:
  - index.md
  - Tutorials:
    - tutorials/index.md
  - How-Tos:
    - howtos/deployment-guide.md
    - howtos/processing-inputs-from-workspace.md
    - howtos/share-workspace-data.md
  - Technical:
    - technical/system-architecture.md

theme:
  # name: mkdocs
  # name: readthedocs
  name: material # https://squidfunk.github.io/mkdocs-material/creating-your-site/

plugins:
  - autorefs

markdown_extensions:
  - tables
  - toc:
      permalink: ⚓︎
      toc_depth: 4
  - smarty
  - sane_lists
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - abbr
  - attr_list
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
