site_name: EO Exploitation Platform Common Architecture
site_url: https://eoepca.readthedocs.io/
repo_url: https://github.com/EOEPCA/docroot/
edit_uri: "edit/main/docs/"

nav:
  - EOEPCA Documentation:
    - index.md
    - Tutorials:
      - tutorials/mastering-eo-application-packaging-with-CWL.md
      - tutorials/CWL-guide-for-eo.md
    - How-Tos:
      - howtos/deploy-eoepca-to-my-platform.md
      - howtos/processing-inputs-from-workspace.md
      - howtos/share-workspace-data.md
    - Technical:
      - technical/system-architecture.md
      - technical/deployment-guide.md
      - Building Blocks:
        - Resource Discovery: technical/resource-discovery-bb.md
        - Resource Registration: technical/resource-registration-bb.md
        - Data Access: technical/data-access-bb.md
        - MLOps: technical/mlops-bb.md
        - Federated Orchestrator: technical/federated-orchestrator-bb.md
        - Identity & Access Management: technical/iam-bb.md
        - Example (template): technical/BB-example.md
  - System Architecture: /projects/architecture/
  - Deployment Guide: /projects/deploy/

theme:
  # name: mkdocs
  # name: readthedocs
  name: material # https://squidfunk.github.io/mkdocs-material/creating-your-site/
  navigation_depth: 4

  # For `material` theme...
  logo: img/favicon.ico
  favicon: img/favicon.ico
  features:
    # Navigation
    - navigation.expand
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    # - navigation.expand
    # - toc.integrate
    - navigation.top
    # Content
    - content.code.copy
    - content.action.edit
    # Search
    - search.highlight
    - search.share
    - search.suggest

extra_css:
  - css/eoepca.css

plugins:
  - autorefs
  - search
  # - pub-debugger:
  #     console_log:
  #       enabled: true
  #       log_level: INFO
  #     file_log:
  #       enabled: false
  #     zip_log:
  #       enabled: false

markdown_extensions:
  - tables
  - toc:
      permalink: ⚓︎
      toc_depth: 4
  - smarty
  - sane_lists
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - abbr
  - attr_list
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
