site_name: EO Exploitation Platform Common Architecture
# site_url: https://deployment-guide.docs.eoepca.org
# repo_url: https://github.com/EOEPCA/deployment-guide
# edit_uri: ""

nav:
  - index.md
  - Tutorials:
    - tutorials/index.md
  - How-Tos:
    - howtos/my-howto.md
  - Technical:
    - technical/index.md

theme:
  # name: mkdocs
  # name: readthedocs
  name: material # https://squidfunk.github.io/mkdocs-material/creating-your-site/
